/** Marcas atendidas — sección SOMOS MULTIMARCAS (solo automóviles) */
export const MARCAS_MULTIMARCAS = [
  { nombre: 'Audi', logo: 'https://cdn.worldvectorlogo.com/logos/audi-11.svg' },
  { nombre: 'BMW', logo: 'https://cdn.worldvectorlogo.com/logos/bmw-2.svg' },
  { nombre: 'BYD', logo: 'https://cdn.worldvectorlogo.com/logos/byd-1.svg' },
  { nombre: 'Chery', logo: 'https://cdn.worldvectorlogo.com/logos/chery.svg' },
  { nombre: 'Chevrolet', logo: 'https://cdn.worldvectorlogo.com/logos/chevrolet-8.svg' },
  { nombre: 'Citroën', logo: 'https://cdn.worldvectorlogo.com/logos/citroen-2.svg' },
  { nombre: 'Dodge', logo: 'https://cdn.worldvectorlogo.com/logos/dodge-4.svg' },
  { nombre: 'Fiat', logo: 'https://cdn.worldvectorlogo.com/logos/fiat-2.svg' },
  { nombre: 'Ford', logo: 'https://cdn.worldvectorlogo.com/logos/ford-8.svg' },
  { nombre: 'Hyundai', logo: 'https://cdn.worldvectorlogo.com/logos/hyundai.svg' },
  { nombre: 'JAC', logo: 'https://cdn.worldvectorlogo.com/logos/jac.svg' },
  { nombre: 'Jeep', logo: 'https://cdn.worldvectorlogo.com/logos/jeep-6.svg' },
  { nombre: 'Kia', logo: 'https://cdn.worldvectorlogo.com/logos/kia-motors-1.svg' },
  { nombre: 'Lexus', logo: 'https://cdn.worldvectorlogo.com/logos/lexus.svg' },
  { nombre: 'Mazda', logo: 'https://static.wikia.nocookie.net/logopedia/images/4/4b/Mazda_New_2024.svg' },
  { nombre: 'Mercedes-Benz', logo: 'https://cdn.worldvectorlogo.com/logos/mercedes-benz-9.svg' },
  { nombre: 'MG', logo: 'https://cdn.worldvectorlogo.com/logos/mg.svg' },
  { nombre: 'Mitsubishi', logo: 'https://cdn.worldvectorlogo.com/logos/mitsubishi-4.svg' },
  { nombre: 'Nissan', logo: 'https://cdn.worldvectorlogo.com/logos/nissan-6.svg' },
  { nombre: 'Peugeot', logo: 'https://cdn.worldvectorlogo.com/logos/peugeot-2.svg' },
  { nombre: 'Renault', logo: 'https://cdn.worldvectorlogo.com/logos/renault-2.svg' },
  { nombre: 'Subaru', logo: 'https://cdn.worldvectorlogo.com/logos/subaru-3.svg' },
  { nombre: 'Cadillac', logo: 'https://dealer29035.dealeron.com/blogs/7267/wp-content/uploads/2025/04/Cadillac-Logo.png' },
  { nombre: 'Tesla', logo: 'https://upload.wikimedia.org/wikipedia/commons/e/e8/Tesla_logo.png' },
  { nombre: 'Toyota', logo: 'https://cdn.worldvectorlogo.com/logos/toyota-1.svg' },
  { nombre: 'Volkswagen', logo: 'https://cdn.worldvectorlogo.com/logos/volkswagen-5.svg' },
  { nombre: 'Volvo', logo: 'https://cdn.worldvectorlogo.com/logos/volvo-2.svg' },
];
