import { connectDb } from './db.js';
import { getDb } from './db.js';
import { invalidateChatbotCache } from './chatbot.js';

const TSV = `PROVEEDOR	SERVICIO	TIPO	CLASE	VALOR_VENTA
SERVICIOS PROPIOS	ALINEACION 2 LLANTAS	SERV	AUTOMOVIL	60000
SERVICIOS PROPIOS	ALINEACION AUTOMOVIL	SERV	AUTOMOVIL	60000
SERVICIOS PROPIOS	BRILLADA CON CORRECCION LEVE Y PROTECCION ACRILICA	SERV	AUTOMOVIL	300000
SERVICIOS PROPIOS	COMBO 1 - LAVADO GENERAL + LAVADO MOTOR	SERV	AUTOMOVIL	76000
SERVICIOS PROPIOS	COMBO 2 - LAVADO GENERAL + ENCERADO + HIDRATACION PARTES NEGRAS	SERV	AUTOMOVIL	76000
SERVICIOS PROPIOS	COMBO 3 - LAVADO GENERAL + MOTOR + ENCERADO	SERV	AUTOMOVIL	108000
SERVICIOS PROPIOS	COMBO 4 - LAVADO GENERAL + ENCERADO + LAV. MOTOR A VAPOR	SERV	AUTOMOVIL	140000
SERVICIOS PROPIOS	COMBO 7 - LAVADO GENERAL + HIDRATACION DE PARTES NEGRAS	SERV	AUTOMOVIL	65000
SERVICIOS PROPIOS	COMBO LUXURY	SERV	AUTOMOVIL	764000
SERVICIOS PROPIOS	CORRECCION LEVE DE RAYONES POR PIEZAS	SERV	AUTOMOVIL	76000
SERVICIOS PROPIOS	DESCONTAMINADO DE PINTURA	SERV	AUTOMOVIL	230000
SERVICIOS PROPIOS	DESCONTAMINADO E HIDRATACION DE CARTERAS Y TABLEROS	SERV	AUTOMOVIL	190000
SERVICIOS PROPIOS	ENCERADO CLEANER WAX BASICO	SERV	AUTOMOVIL	40000
SERVICIOS PROPIOS	ENCERADO CLEANER WAX CON MAQUINA	SERV	AUTOMOVIL	70000
SERVICIOS PROPIOS	GRAFITADO POR 1/4	SERV	AUTOMOVIL	25000
SERVICIOS PROPIOS	LAVADO COJIN DE BAUL	SERV	AUTOMOVIL	80000
SERVICIOS PROPIOS	LAVADO DE MOTOR EXPRESS	SERV	AUTOMOVIL	40000
SERVICIOS PROPIOS	LAVADO GENERAL EXPRESS	SERV	AUTOMOVIL	45000
SERVICIOS PROPIOS	LAVADO MOTOR A VAPOR	SERV	AUTOMOVIL	70000
SERVICIOS PROPIOS	LAVADO PREMIUM	SERV	AUTOMOVIL	55000
SERVICIOS PROPIOS	LIMPIEZA DE INYECTORES	SERV	AUTOMOVIL	809200
SERVICIOS PROPIOS	LIMPIEZA DE TAPICERIA E INTERIOR CON DESMONTE	SERV	AUTOMOVIL	510000
SERVICIOS PROPIOS	LIMPIEZA DE TAPICERIA E INTERIOR SIN DESMONTE	SERV	AUTOMOVIL	450000
SERVICIOS PROPIOS	LIMPIEZA DE TECHO	SERV	AUTOMOVIL	110000
SERVICIOS PROPIOS	LIMPIEZA E HIDRATACION DE CARTERAS Y TABLEROS	SERV	AUTOMOVIL	190000
SERVICIOS PROPIOS	LIMPIEZA PULIDO Y SELLADO DE FAROS	SERV	AUTOMOVIL	140000
SERVICIOS PROPIOS	LIMPIEZA, DESCONTAMINACION, PULIDO Y SELLADO POR RIN	SERV	AUTOMOVIL	195000
SERVICIOS PROPIOS	PROTECCION ANTICORROSIVA	SERV	AUTOMOVIL	1000000
SERVICIOS PROPIOS	REFUERZO DE SOPORTES DE PISOS DELANTEROS	SERV	AUTOMOVIL	800000
SERVICIOS PROPIOS	ROTACION LLANTA	SERV	AUTOMOVIL	30000
SERVICIOS PROPIOS	TRATAMIENTO NANO CERAMICO	SERV	AUTOMOVIL	1300000
SERVICIOS PROPIOS	ALINEACION 2 LLANTAS	SERV	CAMIONETA	80000
SERVICIOS PROPIOS	BALANCEO 4 LLANTAS CAMIONETA	SERV	CAMIONETA	80000
SERVICIOS PROPIOS	BRILLADA CON CORRECCION LEVE Y PROTECCION ACRILICA	SERV	CAMIONETA	445000
SERVICIOS PROPIOS	CAMBIO DE EXPLORADORA	SERV	CAMIONETA	80000
SERVICIOS PROPIOS	CARROCERIA PISO INTERNO	SERV	CAMIONETA	297500
SERVICIOS PROPIOS	COMBO 1 - LAVADO GENERAL + LAVADO MOTOR	SERV	CAMIONETA	89000
SERVICIOS PROPIOS	COMBO 2 - LAVADO GENERAL + ENCERADO + HIDRATACION PARTES NEGRAS	SERV	CAMIONETA	89000
SERVICIOS PROPIOS	COMBO 3 - LAVADO GENERAL + MOTOR + ENCERADO	SERV	CAMIONETA	121000
SERVICIOS PROPIOS	COMBO 4 - LAVADO GENERAL + ENCERADO + LAV. MOTOR A VAPOR	SERV	CAMIONETA	172000
SERVICIOS PROPIOS	COMBO 6 - LAVADO GENERAL + ENCERADO	SERV	CAMIONETA	76000
SERVICIOS PROPIOS	COMBO 7 - LAVADO GENERAL + HIDRATACION DE PARTES NEGRAS	SERV	CAMIONETA	75000
SERVICIOS PROPIOS	COMBO LUXURY	SERV	CAMIONETA	891000
SERVICIOS PROPIOS	CORRECCION LEVE DE RAYONES POR PIEZAS	SERV	CAMIONETA	105000
SERVICIOS PROPIOS	DESCONTAMINACION DE RINES POR DENTRO Y POR FUERA	SERV	CAMIONETA	150000
SERVICIOS PROPIOS	DESCONTAMINADO DE PINTURA	SERV	CAMIONETA	150000
SERVICIOS PROPIOS	DESCONTAMINADO DE VIDRIO	SERV	CAMIONETA	250000
SERVICIOS PROPIOS	DESCONTAMINADO E HIDRATACION DE CARTERAS Y TABLEROS	SERV	CAMIONETA	230000
SERVICIOS PROPIOS	ENCERADO CLEANER WAX BASICO	SERV	CAMIONETA	50000
SERVICIOS PROPIOS	ENCERADO CLEANER WAX CON MAQUINA	SERV	CAMIONETA	80000
SERVICIOS PROPIOS	GRAFITADO POR 1/4	SERV	CAMIONETA	25000
SERVICIOS PROPIOS	LAVADO DE BUS	SERV	CAMIONETA	100000
SERVICIOS PROPIOS	LAVADO DE MOTOR EXPRESS	SERV	CAMIONETA	45000
SERVICIOS PROPIOS	LAVADO GENERAL + COJINERIA	SERV	CAMIONETA	250000
SERVICIOS PROPIOS	LAVADO GENERAL EXPRESS	SERV	CAMIONETA	50000
SERVICIOS PROPIOS	LAVADO MOTOR A VAPOR	SERV	CAMIONETA	90000
SERVICIOS PROPIOS	LAVADO PREMIUM	SERV	CAMIONETA	65000
SERVICIOS PROPIOS	LAVADO PURPLE WATH CHASIS	SERV	CAMIONETA	180000
SERVICIOS PROPIOS	LIMPIEZA COJINERIA CON DESMONTE	SERV	CAMIONETA	250000
SERVICIOS PROPIOS	LIMPIEZA DE TAPICERIA E INTERIOR CON DESMONTE	SERV	CAMIONETA	573000
SERVICIOS PROPIOS	LIMPIEZA DE TAPICERIA E INTERIOR SIN DESMONTE	SERV	CAMIONETA	510000
SERVICIOS PROPIOS	LIMPIEZA DE TECHO	SERV	CAMIONETA	130000
SERVICIOS PROPIOS	LIMPIEZA E HIDRATACION DE CARTERAS Y TABLEROS	SERV	CAMIONETA	230000
SERVICIOS PROPIOS	LIMPIEZA PULIDO Y SELLADO DE FAROS	SERV	CAMIONETA	130000
SERVICIOS PROPIOS	LIMPIEZA, DESCONTAMINACION, PULIDO Y SELLADO POR RIN	SERV	CAMIONETA	204000
SERVICIOS PROPIOS	MANO DE OBRA CAMBIO DE ACEITE	SERV	CAMIONETA	60000
SERVICIOS PROPIOS	PINTURA INTERIOR CARROCERIA	SERV	CAMIONETA	357000
SERVICIOS PROPIOS	POLARIZADO AUTOMOVIL NANOCERAMICO 60%	SERV	CAMIONETA	600000
SERVICIOS PROPIOS	POLARIZADO NANOCERAMICO	SERV	CAMIONETA	800000
SERVICIOS PROPIOS	PROTECCION ANTICORROSIVA	SERV	CAMIONETA	1200000
SERVICIOS PROPIOS	ROTACION DE LLANTA	SERV	CAMIONETA	40000
SERVICIOS PROPIOS	SERVICIO DE SCANER	PROD	CAMIONETA	140000
SERVICIOS PROPIOS	TRATAMIENTO NANO CERAMICO	SERV	CAMIONETA	1200000
SERVICIOS PROPIOS	LAVADO DE MOTOCICLETA	SERV	MOTO	40000
SERVICIOS PROPIOS	LAVADO GENERAL	SERV	MOTO	38000
SERVICIOS PROPIOS	LAVADO GENERAL + ENCERADO	SERV	MOTO	43000
SERVICIOS PROPIOS	LAVADO GENERAL + GRAFITADO	SERV	MOTO	43000
SERVICIOS PROPIOS	NANOCERAMICO MOTOS	SERV	MOTO	800000
SERVICIOS PROPIOS	ADICIONAL LAVADO	SERV	XTODOS	10000
SERVICIOS PROPIOS	AJUSTE DE CAJETA	SERV	XTODOS	100000
SERVICIOS PROPIOS	AJUSTE DE EXTENSION PLASTICA	SERV	XTODOS	100000
SERVICIOS PROPIOS	ALINEACION 4 LLANTAS	SERV	XTODOS	140000
SERVICIOS PROPIOS	ALINEACION DE LUCES	SERV	XTODOS	40000
SERVICIOS PROPIOS	ANALISIS CON SCANER	SERV	XTODOS	120000
SERVICIOS PROPIOS	APLICACION DE WD40	SERV	XTODOS	30000
SERVICIOS PROPIOS	APLICACION SPRAY W40	SERV	XTODOS	40000
SERVICIOS PROPIOS	BALANCEO 1	SERV	XTODOS	15000
SERVICIOS PROPIOS	BALANCEO 2 LLANTAS	SERV	XTODOS	40000
SERVICIOS PROPIOS	BALANCEO 4 LLANTAS	SERV	XTODOS	60000
SERVICIOS PROPIOS	CALIBRACION DE LLANTAS	SERV	XTODOS	2500
SERVICIOS PROPIOS	CAMBIO ESTRIBO DERECHO	SERV	XTODOS	714000
SERVICIOS PROPIOS	CAMBIO COLA DE GUARDABARRO IZQ	SERV	XTODOS	297500
SERVICIOS PROPIOS	CAMBIO CONDENSADOR AIRE ACONDICIONADO	SERV	XTODOS	830000
SERVICIOS PROPIOS	CAMBIO CONTRACAJETA DERECHA	SERV	XTODOS	476000
SERVICIOS PROPIOS	CAMBIO DE ACEITE Y FILTROS	SERV	XTODOS	67000
SERVICIOS PROPIOS	CAMBIO DE BATERIA	SERV	XTODOS	30000
SERVICIOS PROPIOS	CAMBIO DE BATERIA A DOMICILIO	SERV	XTODOS	50000
SERVICIOS PROPIOS	CAMBIO DE BOMBILLO DE LAMPARA	SERV	XTODOS	20000
SERVICIOS PROPIOS	CAMBIO DE CAJA DE DIRRECION	SERV	XTODOS	238000
SERVICIOS PROPIOS	CAMBIO DE CAJETAS	SERV	XTODOS	952000
SERVICIOS PROPIOS	CAMBIO DE EMPAQUE	SERV	XTODOS	261800
SERVICIOS PROPIOS	CAMBIO DE PASTILLAS	SERV	XTODOS	80000
SERVICIOS PROPIOS	CAMBIO DE PASTILLAS DE FRENOS	SERV	XTODOS	280000
SERVICIOS PROPIOS	CAMBIO DE TAPICERIA DE TECHO	SERV	XTODOS	1700000
SERVICIOS PROPIOS	CAMBIO DE VIDRIO PANORAMICO	SERV	XTODOS	1011500
SERVICIOS PROPIOS	CAMBIO SOPORTE PISO DERECHO	SERV	XTODOS	545000
SERVICIOS PROPIOS	CAMBIOS DE AMORTIGUADORES TRASEROS	SERV	XTODOS	357000
SERVICIOS PROPIOS	CARGA DE NITROGENO	SERV	XTODOS	10000
SERVICIOS PROPIOS	CARROCERIA BAUL PISO	SERV	XTODOS	297000
SERVICIOS PROPIOS	COMBO 5 - LAVADO LLANTAS + LAVADO MOTOR VAPOR	SERV	XTODOS	89000
SERVICIOS PROPIOS	DESCONTAMINACION DE VIDRIOS	SERV	XTODOS	230000
SERVICIOS PROPIOS	DESCONTAMINADO DE RINES CON DESMONTE	SERV	XTODOS	160000
SERVICIOS PROPIOS	DESENGRASANTE	SERV	XTODOS	10000
SERVICIOS PROPIOS	DESMONTE DE SILLA	SERV	XTODOS	400000
SERVICIOS PROPIOS	DESMONTE Y MONTE DE TIJERAS DELANTERAS	SERV	XTODOS	333200
SERVICIOS PROPIOS	DESMONTE Y MONTE DEFENSA DELANTERA	SERV	XTODOS	119000
SERVICIOS PROPIOS	DESMONTE Y MONTE VENTILADOR	SERV	XTODOS	297000
SERVICIOS PROPIOS	DESTRABE MANTENIENTOS COJINES RECLINABLES TOYOTA	SERV	XTODOS	400000
SERVICIOS PROPIOS	DETAILING BASICO TAPICERIA 2	SERV	XTODOS	300000
SERVICIOS PROPIOS	DIAGNOSTICO DE SUSPENSION	SERV	XTODOS	100000
SERVICIOS PROPIOS	DIAGNOSTICO DE FRENOS	SERV	XTODOS	40000
SERVICIOS PROPIOS	DIAGNOSTICO SINCRONIZACION	SERV	XTODOS	80000
SERVICIOS PROPIOS	GRASA	SERV	XTODOS	20000
SERVICIOS PROPIOS	HIDROBLASTING	SERV	XTODOS	1200000
SERVICIOS PROPIOS	INSUMO	SERV	XTODOS	95200
SERVICIOS PROPIOS	LATONERIA BOTE	SERV	XTODOS	416500
SERVICIOS PROPIOS	LATONERIA CAJETA	SERV	XTODOS	200000
SERVICIOS PROPIOS	LATONERIA COSTADO INTERIOR	SERV	XTODOS	238000
SERVICIOS PROPIOS	LATONERIA DE CUNA	SERV	XTODOS	500000
SERVICIOS PROPIOS	LATONERIA GENERAL	SERV	XTODOS	238000
SERVICIOS PROPIOS	LATONERIA GUARDABARRO DELANTERO DERECHO	SERV	XTODOS	357000
SERVICIOS PROPIOS	LATONERIA GUARDABARRO TRASERO DERECHO	SERV	XTODOS	357000
SERVICIOS PROPIOS	LATONERIA GUARDABARRO TRASERO IZQUIERDO	SERV	XTODOS	357000
SERVICIOS PROPIOS	LATONERIA PUERTA TRASERA	SERV	XTODOS	535500
SERVICIOS PROPIOS	LATONERIA RECORRIDO DE GOLPES	SERV	XTODOS	200000
SERVICIOS PROPIOS	LATONERIA REPARACION PISO	SERV	XTODOS	416500
SERVICIOS PROPIOS	LAVADO DE AGUA CALIENTE	SERV	XTODOS	390000
SERVICIOS PROPIOS	LAVADO SOLO CON AGUA	SERV	XTODOS	20000
SERVICIOS PROPIOS	LIMPIEZA ADICIONAL	SERV	XTODOS	10000
SERVICIOS PROPIOS	LIMPIEZA DE PISO	SERV	XTODOS	150000
SERVICIOS PROPIOS	LIMPIEZA DE TAPICERIA	SERV	XTODOS	220000
SERVICIOS PROPIOS	LIMPIEZA DE TAPICERIA PARTE DELANTERA IZQUIERDA	SERV	XTODOS	80000
SERVICIOS PROPIOS	LLANTERIA	SERV	XTODOS	40000
SERVICIOS PROPIOS	MANO DE OBRA	SERV	XTODOS	333200
SERVICIOS PROPIOS	MANO DE OBRA DESMONTE MONTE ARRANQUE	SERV	XTODOS	180000
SERVICIOS PROPIOS	MANO DE OBRA FRENO	SERV	XTODOS	120000
SERVICIOS PROPIOS	MANO DE OBRA CAMBIO DE ACEITE	SERV	XTODOS	30000
SERVICIOS PROPIOS	MANO DE OBRA REFRIGERACION	SERV	XTODOS	850850
SERVICIOS PROPIOS	MANO OBRA CHIP	SERV	XTODOS	30000
SERVICIOS PROPIOS	MANTENIMIENTO LIMPIA PARABRISA	SERV	XTODOS	120000
SERVICIOS PROPIOS	MANTENIMIENTO AIRE ACONDICIONADO	SERV	XTODOS	690000
SERVICIOS PROPIOS	MANTENIMIENTO CALIPER	SERV	XTODOS	250000
SERVICIOS PROPIOS	MANTENIMIENTO CERAMICO	SERV	XTODOS	300000
SERVICIOS PROPIOS	MANTENIMIENTO DE CALIPER	SERV	XTODOS	142800
SERVICIOS PROPIOS	MANTENIMIENTO DE FRENOS	SERV	XTODOS	140000
SERVICIOS PROPIOS	MANTENIMIENTO RINES	SERV	XTODOS	60000
SERVICIOS PROPIOS	MANTENIMIENTO SWITCH ELEVAVIDRIOS Y COMANDO PRINCIPAL	SERV	XTODOS	571200
SERVICIOS PROPIOS	MONTAJE DE LLANTA BLINDADAS	SERV	XTODOS	119000
SERVICIOS PROPIOS	MONTAJE DE LLANTAS	SERV	XTODOS	40000
SERVICIOS PROPIOS	OTROS DETAILING TAPICERIA	SERV	XTODOS	350000
SERVICIOS PROPIOS	PARQUEO	SERV	XTODOS	15000
SERVICIOS PROPIOS	PINTURA GUARDABARROS	SERV	XTODOS	357000
SERVICIOS PROPIOS	PINTURA BOMPER DELANTERO	SERV	XTODOS	470000
SERVICIOS PROPIOS	PINTURA BOMPER TRASERO	SERV	XTODOS	400000
SERVICIOS PROPIOS	PINTURA CAJETAS	SERV	XTODOS	300000
SERVICIOS PROPIOS	PINTURA COMPUERTA TRASERA	SERV	XTODOS	280000
SERVICIOS PROPIOS	PINTURA COSTADO IZQ	SERV	XTODOS	357000
SERVICIOS PROPIOS	PINTURA DE COSTADO DE LA CAMIONETA	SERV	XTODOS	480000
SERVICIOS PROPIOS	PINTURA DE ESTRIBO	SERV	XTODOS	476000
SERVICIOS PROPIOS	PINTURA DE PUERTAS	SERV	XTODOS	800000
SERVICIOS PROPIOS	PINTURA DE RIN DERECHO DELANTERO	SERV	XTODOS	200000
SERVICIOS PROPIOS	PINTURA DEFENSA TRASERA	SERV	XTODOS	350000
SERVICIOS PROPIOS	PINTURA GENERAL EXTERIOR	SERV	XTODOS	3400000
SERVICIOS PROPIOS	PINTURA GUARDABARROS TRASERO	SERV	XTODOS	250000
SERVICIOS PROPIOS	PINTURA MANIJA	SERV	XTODOS	100000
SERVICIOS PROPIOS	PINTURA PERFIL DEFENSA	SERV	XTODOS	120000
SERVICIOS PROPIOS	PINTURA PLACA	SERV	XTODOS	100000
SERVICIOS PROPIOS	PINTURA PUERTA TRASERA	SERV	XTODOS	416500
SERVICIOS PROPIOS	PINTURA PUNTUAL BOMPER DELANTERO	SERV	XTODOS	100000
SERVICIOS PROPIOS	PINTURA TAPA BAUL	SERV	XTODOS	480000
SERVICIOS PROPIOS	PINTURA TRES PIEZA	SERV	XTODOS	1200000
SERVICIOS PROPIOS	PINTURAS PUERTAS DERECHAS	SERV	XTODOS	400000
SERVICIOS PROPIOS	POLARIZADO DE VIDRIO PANORAMICO DELANTERO	SERV	XTODOS	250000
SERVICIOS PROPIOS	POLARIZADO PANORAMICO VIDRIO TRASERO	SERV	XTODOS	80000
SERVICIOS PROPIOS	POLARIZADO PANORAMICO Y VENTANAS	SERV	XTODOS	550000
SERVICIOS PROPIOS	POLICHADA GENERAL	SERV	XTODOS	450000
SERVICIOS PROPIOS	PROGRAMACION SENSOR LLANTA	SERV	XTODOS	238000
SERVICIOS PROPIOS	PULIDO DE PIEZA	SERV	XTODOS	60000
SERVICIOS PROPIOS	RECTIFICADORA DISCO X 2	SERV	XTODOS	65000
SERVICIOS PROPIOS	REMOCION DE RAYON PUNTUAL	SERV	XTODOS	50000
SERVICIOS PROPIOS	REP PUERTA TRASERA DERECHA	SERV	XTODOS	416500
SERVICIOS PROPIOS	REPARACION AIRE ACONDICIONADO	SERV	XTODOS	250000
SERVICIOS PROPIOS	REPARACION ALTERNADOR	SERV	XTODOS	400000
SERVICIOS PROPIOS	REPARACION BOMPER	SERV	XTODOS	390000
SERVICIOS PROPIOS	REPARACION COSTADO DERECHO	SERV	XTODOS	416500
SERVICIOS PROPIOS	REPARACION DE ELEVA VIDRIOS DE PUERTAS	SERV	XTODOS	71400
SERVICIOS PROPIOS	REPARACION DE ESTRIBO DERECHO	SERV	XTODOS	100000
SERVICIOS PROPIOS	REPARACION DE MOFLE	SERV	XTODOS	20000
SERVICIOS PROPIOS	REPARACION DE PLATON	SERV	XTODOS	595000
SERVICIOS PROPIOS	REPARACION ESTRIBO DERECHO	SERV	XTODOS	100000
SERVICIOS PROPIOS	REPARACION LATONERIA PUERTA TRASERA REPARACION MANIJA	SERV	XTODOS	357000
SERVICIOS PROPIOS	REPARACION PISO INTERNO	SERV	XTODOS	238000
SERVICIOS PROPIOS	REPARACION PROTECTOR PLASTICO DE SILLA DELANTERA	SERV	XTODOS	100000
SERVICIOS PROPIOS	REPARACION SOPORTE AMORTIGUADORES TRASEROS	SERV	XTODOS	238000
SERVICIOS PROPIOS	REPARACION TREN TRASERO	SERV	XTODOS	600000
SERVICIOS PROPIOS	REPARACION VIDRIO PANORAMICO	SERV	XTODOS	280000
SERVICIOS PROPIOS	REPARACION Y MANTENIMIENTO ARRANQUE	SERV	XTODOS	170000
SERVICIOS PROPIOS	REPARCAION DE VENTILADOR	SERV	XTODOS	285600
SERVICIOS PROPIOS	RETOQUE HIDROBLASTING	SERV	XTODOS	238000
SERVICIOS PROPIOS	RETOQUE PROTECCION	SERV	XTODOS	800000
SERVICIOS PROPIOS	RETOQUE PUNTUAL LADO IZQUIERDO DEFENSA DELANTERA	SERV	XTODOS	120000
SERVICIOS PROPIOS	REVISION DE BATERIA	SERV	XTODOS	20000
SERVICIOS PROPIOS	REVISION DE FRENO	SERV	XTODOS	80000
SERVICIOS PROPIOS	REVISION SUSPENSION	SERV	XTODOS	15000
SERVICIOS PROPIOS	SERVICIO A DOMICILIO	SERV	XTODOS	10000
SERVICIOS PROPIOS	SERVICIO DE PRENSA	SERV	XTODOS	47600
SERVICIOS PROPIOS	SERVICIO DE SCANNER	SERV	XTODOS	150000
SERVICIOS PROPIOS	SERVICIO DE SELLAMIENTO DE CARROCERIA IZQUIERDO	SERV	XTODOS	90000
SERVICIOS PROPIOS	SERVICIOS DE LABORATORIO PRUEBA DE INYECTORESGDI	SERV	XTODOS	680000
SERVICIOS PROPIOS	SERVICIOS DE VALVULAS	SERV	XTODOS	70000
SERVICIOS PROPIOS	SINCRONIZACION (CABLES, BOBINA)	SERV	XTODOS	350000
SERVICIOS PROPIOS	UNIDO Y SELLADO DE RINES	SERV	XTODOS	70000`;

interface RawRow {
  servicio: string;
  tipo: string;
  clase: string;
  valor: number;
}

interface ServicioDoc {
  nombre: string;
  descripcion: string;
  categoria: string;
  items: string[];
  precio_base: number;
  precio_auto: number;
  precio_camioneta: number;
  precio_moto: number;
  iva_incluido: boolean;
  duracion_minutos: number;
  agendable: boolean;
  activo: boolean;
  icono: string;
  imagen_url: string;
  color: string;
  orden: number;
  cotizar_local: boolean;
  created_at: Date;
}

function isExcluded(nombre: string): boolean {
  const n = nombre.toUpperCase().normalize('NFKD').replace(/[^\w\s]/g, '');
  const patterns = [
    // Latonería
    /\bLATONERIA\b/,
    // Pintura (solo si empieza con PINTURA, no si contiene "DE PINTURA")
    /^PINTURA\b/,
    /^PINTURAS\b/,
    /^POLICHADA\b/,
    /^PINTURA INTERIOR CARROCERIA\b/,
    // Mecánica: cambios/reemplazos de partes
    /^CAMBIO(S)?\b/,
    // Mecánica: mano de obra
    /^MANO DE OBRA\b/,
    /^MANO OBRA\b/,
    // Mecánica: reparaciones
    /^REPARACION\b/,
    /^REPARCAION\b/,
    /^REP PUERTA\b/,
    /^REPARACION LATONERIA\b/,
    // Mecánica: mantenimiento de componentes mecánicos
    /^MANTENIMIENTO (LIMPIA PARABRISA|AIRE ACONDICIONADO|CALIPER|DE CALIPER|DE FRENOS|SWITCH)/,
    // Mecánica: diagnóstico
    /^DIAGNOSTICO\b/,
    // Mecánica: desmonte/monte
    /^DESMONTE\b/,
    /^MONTAJE\b/,
    // Mecánica: ajustes
    /^AJUSTE\b/,
    // Mecánica: otros
    /^SINCRONIZACION\b/,
    /^REFUERZO\b/,
    /^RECTIFICADORA\b/,
    /^PROGRAMACION\b/,
    /^SERVICIOS DE LABORATORIO\b/,
    /^SERVICIOS DE VALVULAS\b/,
    /^UNIDO Y SELLADO DE RINES\b/,
    /^CARGA DE NITROGENO\b/,
    /^SERVICIO DE PRENSA\b/,
    /^REVISION\b/,
    /^CARROCERIA\b/,
    /^RETOQUE PUNTUAL\b/,
    // Mecánica: cambios de partes específicas
    /^CAMBIOS\b/,
  ];
  return patterns.some(p => p.test(n));
}

function inferCategoria(nombre: string): string {
  const n = nombre.toUpperCase();
  if (/COMBO/.test(n)) return 'Combos';
  if (/LAVADO|HIDRATACION/.test(n)) return 'Lavado y Detailing';
  if (/ENCERADO|BRILLADA|CORRECCION|PROTECCION ACRILICA/.test(n)) return 'Detailing y Protección';
  if (/NANO CERAMICO|NANOCERAMICO/.test(n)) return 'Detailing y Protección';
  if (/DESCONTAMINADO|DESCONTAMINACION/.test(n)) return 'Detailing y Protección';
  if (/ALINEACION|BALANCEO|ROTACION/.test(n)) return 'Mantenimiento Básico';
  if (/POLARIZADO/.test(n)) return 'Polarizados';
  if (/LIMPIEZA.*FAROS|PULIDO.*FAROS|SELLADO.*FAROS/.test(n)) return 'Faros';
  if (/RIN|RINES/.test(n)) return 'Rines';
  if (/LIMPIEZA.*TAPICERIA|LIMPIEZA.*INTERIOR|LIMPIEZA.*TECHO|LIMPIEZA.*COJIN|DETAILING/.test(n)) return 'Limpieza Profunda';
  if (/PROTECCION ANTICORROSIVA/.test(n)) return 'Protección';
  if (/GRAFITADO/.test(n)) return 'Lavado y Detailing';
  if (/HIDROBLASTING/.test(n)) return 'Hidroblasting';
  if (/SERVICIO.*SCAN|SERVICIO.*SCANNER|ANALISIS CON SCANER/.test(n)) return 'Diagnóstico';
  if (/MOTOCICLETA|MOTO/.test(n)) return 'Lavado y Detailing';
  if (/ADICIONAL|DESENGRASANTE|GRASA|INSUMO|LIMPIEZA ADICIONAL|PARQUEO|LLANTERIA|APLICACION/.test(n)) return 'Adicionales';
  if (/PULIDO DE PIEZA|REMOCION DE RAYON/.test(n)) return 'Detailing y Protección';
  if (/SERVICIO A DOMICILIO/.test(n)) return 'Adicionales';
  if (/AGUA CALIENTE|SOLO CON AGUA/.test(n)) return 'Lavado y Detailing';
  return 'Lavado y Detailing';
}

function inferIcono(categoria: string, nombre: string): string {
  const n = nombre.toUpperCase();
  if (categoria === 'Combos') return 'local_offer';
  if (/NANO/.test(n)) return 'auto_awesome';
  if (/LAVADO/.test(n)) return 'local_car_wash';
  if (/POLARIZADO/.test(n)) return 'dark_mode';
  if (/FAROS/.test(n)) return 'lightbulb';
  if (/RINES|RIN/.test(n)) return 'circle';
  if (/LIMPIEZA.*TAPICERIA|DETAILING/.test(n)) return 'chair';
  if (/PROTECCION/.test(n)) return 'shield';
  if (/ALINEACION|BALANCEO/.test(n)) return 'swap_calls';
  if (/HIDROBLASTING/.test(n)) return 'water_jet';
  if (/MOTO/.test(n)) return 'two_wheeler';
  return 'auto_awesome';
}

function inferDuracion(nombre: string): number {
  const n = nombre.toUpperCase();
  if (/NANO CERAMICO|NANOCERAMICO|COMBO LUXURY|PROTECCION ANTICORROSIVA|HIDROBLASTING/.test(n)) return 240;
  if (/LIMPIEZA.*TAPICERIA.*DESMONTE|LIMPIEZA.*INTERIOR.*DESMONTE/.test(n)) return 360;
  if (/BRILLADA.*CORRECCION|TRATAMIENTO/.test(n)) return 180;
  if (/COMBO [3-7]|DESCONTAMINADO|LIMPIEZA.*TAPICERIA|LIMPIEZA.*CARTERAS/.test(n)) return 120;
  if (/COMBO|LAVADO.*MOTOR.*VAPOR|ENCERADO.*MAQUINA|LIMPIEZA.*TECHO/.test(n)) return 90;
  if (/LAVADO PREMIUM|LAVADO.*COJIN|LIMPIEZA.*FAROS|DESCONTAMINACION.*RINES/.test(n)) return 60;
  if (/ALINEACION|BALANCEO|ROTACION|GRAFITADO/.test(n)) return 30;
  if (/LAVADO GENERAL|LAVADO.*EXPRESS|LAVADO.*MOTOR/.test(n)) return 45;
  if (/ADICIONAL|PARQUEO|CALIBRACION|APLICACION/.test(n)) return 15;
  if (/MOTO/.test(n)) return 30;
  return 60;
}

function normalizeNombre(s: string): string {
  return s.trim().replace(/\s+/g, ' ');
}

async function migrate() {
  const database = await connectDb();
  console.log('[migrate-servicios] Conectado a MongoDB');

  const lines = TSV.split('\n').map(l => l.trim()).filter(l => l.length > 0);
  const header = lines[0].split('\t');
  const rawRows: RawRow[] = [];

  for (let i = 1; i < lines.length; i++) {
    const cols = lines[i].split('\t');
    if (cols.length < 5) continue;
    rawRows.push({
      servicio: normalizeNombre(cols[1]),
      tipo: cols[2].trim(),
      clase: cols[3].trim(),
      valor: parseInt(cols[4].replace(/\./g, ''), 10),
    });
  }

  console.log(`[migrate-servicios] Total filas leídas: ${rawRows.length}`);

  const excluded = rawRows.filter(r => isExcluded(r.servicio));
  const excludedNames = [...new Set(excluded.map(r => r.servicio))];
  console.log(`[migrate-servicios] Excluidos (${excluded.length} filas, ${excludedNames.length} servicios):`);
  for (const name of excludedNames.sort()) {
    console.log(`  - ${name}`);
  }

  const filtered = rawRows.filter(r => !isExcluded(r.servicio));
  const includedNames = [...new Set(filtered.map(r => r.servicio))].sort();
  console.log(`[migrate-servicios] Filas después de exclusión: ${filtered.length}`);
  console.log(`[migrate-servicios] Servicios incluidos (${includedNames.length}):`);
  for (const name of includedNames) {
    console.log(`  + ${name}`);
  }

  const grouped = new Map<string, { auto: number | null; camioneta: number | null; moto: number | null; xtodos: number | null }>();
  const orderMap = new Map<string, number>();

  for (const row of filtered) {
    if (!grouped.has(row.servicio)) {
      grouped.set(row.servicio, { auto: null, camioneta: null, moto: null, xtodos: null });
      orderMap.set(row.servicio, orderMap.size + 1);
    }
    const g = grouped.get(row.servicio)!;

    if (row.clase === 'XTODOS') {
      g.xtodos = row.valor;
    } else if (row.clase === 'AUTOMOVIL') {
      g.auto = row.valor;
    } else if (row.clase === 'CAMIONETA') {
      g.camioneta = row.valor;
    } else if (row.clase === 'MOTO') {
      g.moto = row.valor;
    }
  }

  console.log(`[migrate-servicios] Servicios únicos agrupados: ${grouped.size}`);

  const docs: ServicioDoc[] = [];
  let orden = 0;

  for (const [nombre, prices] of grouped) {
    orden++;
    const precioAuto = prices.auto ?? prices.xtodos ?? 0;
    const precioCamioneta = prices.camioneta ?? prices.xtodos ?? 0;
    const precioMoto = prices.moto ?? (prices.xtodos ?? 0);
    const precioBase = Math.min(precioAuto, precioCamioneta, precioMoto) || precioAuto;
    const categoria = inferCategoria(nombre);
    const icono = inferIcono(categoria, nombre);
    const duracion = inferDuracion(nombre);

    docs.push({
      nombre,
      descripcion: `Servicio de ${nombre.toLowerCase()} para vehículos`,
      categoria,
      items: [],
      precio_base: precioBase,
      precio_auto: precioAuto,
      precio_camioneta: precioCamioneta,
      precio_moto: precioMoto,
      iva_incluido: true,
      duracion_minutos: duracion,
      agendable: true,
      activo: true,
      icono,
      imagen_url: '',
      color: '#ff2b2b',
      orden,
      cotizar_local: false,
      created_at: new Date(),
    });
  }

  const coleccion = database.collection('servicios');
  const oldCount = await coleccion.countDocuments();
  console.log(`[migrate-servicios] Servicios actuales en BD: ${oldCount}`);

  await coleccion.deleteMany({});
  console.log('[migrate-servicios] Servicios antiguos eliminados');

  await coleccion.insertMany(docs);
  console.log(`[migrate-servicios] Insertados ${docs.length} servicios nuevos`);

  await coleccion.createIndex({ categoria: 1, orden: 1 });

  invalidateChatbotCache();
  console.log('[migrate-servicios] Caché del chatbot invalidada');

  console.log('\n✅ Migración completada exitosamente');
  console.log(`   Servicios eliminados: ${oldCount}`);
  console.log(`   Servicios insertados: ${docs.length}`);

  const cats = [...new Set(docs.map(d => d.categoria))].sort();
  console.log(`   Categorías: ${cats.join(', ')}`);

  process.exit(0);
}

migrate().catch(err => {
  console.error('❌ Error en migración:', err);
  process.exit(1);
});
