name = "luxury-worker"
main = "src/index.ts"
compatibility_date = "2025-01-01"
node_compat = true

[triggers]
crons = ["0 0 * * *"]

[vars]
JWT_SECRET = "cambiar-por-un-secreto-seguro"
DATA_API_URL = "https://data.mongodb-api.com/app/TU_APP_ID/endpoint/data/v1"
DATA_SOURCE = "luxury-servive-manga"
ADMIN_EMAIL = "admin@luxuryservice.co"
BASE_URL = "https://luxuryservice.co"
